"""titulaire_compte

Revision ID: 34de09ff651d
Revises: d7c6b8c1eb1b
Create Date: 2023-03-20 19:20:01.733313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34de09ff651d'
down_revision = 'd7c6b8c1eb1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulaire_compte',
    sa.Column('titulaire_id', sa.Integer(), nullable=True),
    sa.Column('compte_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compte_id'], ['diasporaapp_compte.id'], ),
    sa.ForeignKeyConstraint(['titulaire_id'], ['Titulaire.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titulaire_compte')
    # ### end Alembic commands ###
