"""operation

Revision ID: 7b76921376b9
Revises: 34de09ff651d
Create Date: 2023-03-20 19:23:16.567329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b76921376b9'
down_revision = '34de09ff651d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diasporaapp_operation', sa.Column('Compte_cpte_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diasporaapp_operation', 'diasporaapp_compte', ['Compte_cpte_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diasporaapp_operation', type_='foreignkey')
    op.drop_column('diasporaapp_operation', 'Compte_cpte_id')
    # ### end Alembic commands ###
