"""second

Revision ID: d7c6b8c1eb1b
Revises: 
Create Date: 2023-03-20 19:12:11.214009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c6b8c1eb1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Titulaire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tit_nom', sa.String(length=255), nullable=True),
    sa.Column('tit_prenom', sa.String(length=255), nullable=True),
    sa.Column('tit_date_nais', sa.DateTime(), nullable=True),
    sa.Column('tit_lieu_nais', sa.String(length=255), nullable=True),
    sa.Column('tit_nationalite', sa.String(length=255), nullable=True),
    sa.Column('tit_profession', sa.String(length=255), nullable=True),
    sa.Column('tit_pays', sa.String(length=255), nullable=True),
    sa.Column('tit_adr_actuelle', sa.String(length=255), nullable=True),
    sa.Column('tit_adr_mg', sa.String(length=255), nullable=True),
    sa.Column('tit_home_tel', sa.String(length=255), nullable=True),
    sa.Column('tit_mob_tel', sa.String(length=255), nullable=True),
    sa.Column('tit_email', sa.String(length=255), nullable=True),
    sa.Column('tit_sexe', sa.String(length=255), nullable=True),
    sa.Column('tit_sit_fam', sa.String(length=255), nullable=True),
    sa.Column('tit_type_piece', sa.String(length=255), nullable=True),
    sa.Column('tit_num_piece', sa.String(length=255), nullable=True),
    sa.Column('tit_date_piece', sa.String(length=255), nullable=True),
    sa.Column('tit_agence', sa.String(length=255), nullable=True),
    sa.Column('pieceidentite', sa.String(length=255), nullable=True),
    sa.Column('cert_residence', sa.String(length=255), nullable=True),
    sa.Column('photoid', sa.String(length=255), nullable=True),
    sa.Column('datecreation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diasporaapp_compte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpte_num', sa.String(length=20), nullable=True),
    sa.Column('cpte_type', sa.String(length=20), nullable=True),
    sa.Column('cpte_date_ouverture', sa.DateTime(), nullable=True),
    sa.Column('cpte_date_cloture', sa.DateTime(), nullable=True),
    sa.Column('cpte_ref_cloture', sa.String(length=20), nullable=True),
    sa.Column('cpte_solde', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diasporaapp_operation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_date', sa.DateTime(), nullable=True),
    sa.Column('op_montant', sa.Integer(), nullable=True),
    sa.Column('op_reference', sa.String(length=45), nullable=True),
    sa.Column('op_partenaire', sa.String(length=45), nullable=True),
    sa.Column('op_etat', sa.String(length=45), nullable=True),
    sa.Column('op_quinze', sa.Integer(), nullable=True),
    sa.Column('op_interet', sa.String(length=2), nullable=True),
    sa.Column('op_annee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('diasporaapp_operation')
    op.drop_table('diasporaapp_compte')
    op.drop_table('Titulaire')
    # ### end Alembic commands ###
